### ISSUE TITLE
how to load images from a /public or /static folder 

### ISSUE THREAD

**Issue by gurugeek** [knarka/woah#10]
Is there an easy way to load images for a website stored in a /public or /static folder?
as workaround I have this

```
on %r{^/public/(.+)\.(png|jpg|jpeg|svg)$} do
   img_file = match[1]+'.'+match[2]
 puts img_file....

```
but may be I am missing the more elegant way ? 
Thanks again for the framework.

**Comment by mxrnx** [comment]
There is no built in way to do this, your solution works quite nicely. I'm trying to keep Woah! as minimal as possible, so there's no plans to add this as a built in feature.

Regarding your solution, it might be wise to check that match[1] does not include the string `".."`, to prevent files above your project's root from being accessed (e.g. `GET /public/../../../someimage.png HTTP/1.1`).
